### ISSUE TITLE
How to get RK result

### ISSUE THREAD

**Issue by pigen01** [RQuispeC/top-dropblock#2]
I have some question about RK, what is the meaning, and how can I find the paper introduce this method?

**Comment by RQuispeC** [comment]
RK stands for re-ranking, there are various papers proposing re-ranking techniques. This repo implements this paper:

Zhong Z, Zheng L, Cao D, et al. Re-ranking Person Re-identification with k-reciprocal Encoding[J]. 2017.

code here:
https://github.com/RQuispeC/top-dropblock/blob/master/torchreid/utils/rerank.py

To get RK results you should change the config file (e.g. [this](https://github.com/RQuispeC/top-dropblock/blob/master/configs/im_bdnet_test.yaml)):
```
test:
  rerank: True
```
