### ISSUE TITLE
How long does it take to finish training?

### ISSUE THREAD

**Issue by kazuki-can** [RQuispeC/top-dropblock#3]
I am training the model, but for each epoch , it takes for about 90 minutes. So , how long does it usually take to finish training?
After each epoch, it says 'Cython evaluation ( very fast so highly recommended) is unavailable, now use python evaluation.

**Comment by RQuispeC** [comment]
It takes some days to train, this time changes depending on the dataset (don't recall exactly).
That 'Cython evaluation...' is because there is a faster implementation for the evaluation step, to activate it you can do

```
cd torchreid/metrics/rank_cylib/
make
```

**Comment by kazuki-can** [comment]
Thank you so much.
And thank you for the past too.
Let me ask you one more thing.
Is there anywhere to get pre-trained model made by --config-file configs/im_top_bdnet_train_market1501.yaml?

**Comment by RQuispeC** [comment]
I may push the trained models in the future, I'm occupied in other projects. Sorry for that

**Comment by kazuki-can** [comment]
It's ok. Thank you so much.

**Comment by RQuispeC** [comment]
Trained models added in README.
Please notice that the models may not give the exact results as on the paper because the reported results 
 are an average of running the model 5 times. However, the difference shouldn't be large.
