### ISSUE TITLE
Test for Custom dataset 

### ISSUE THREAD

**Issue by ghost** [RQuispeC/top-dropblock#5]
Can you please share the instructions for testing using a custom dataset ?

**Comment by RQuispeC** [comment]
You need to define your own class for your dataset, this class should heritage from `ImageDataset`. For instance you can check [this](https://github.com/RQuispeC/top-dropblock/blob/master/torchreid/data/datasets/image/market1501.py)

Make sure you include this line in your class

```
super(Market1501, self).__init__(train, query, gallery, **kwargs)
```

if you aim to only do inference you can leave `train` empty.
