### ISSUE TITLE
coding question

### ISSUE THREAD

**Issue by syh-hue** [RQuispeC/top-dropblock#7]
Hi,sir, when running main.py,getting Extracting features from query set ...,it will happen forward() error such as TypeError: forward() got an unexpected keyword argument 'drop_top'; or TypeError: forward() takes 2 or 3 positional arguments but 4 were given.
That from engine.py and torch's module,
share you help me？i  am Freshman. Thanks very much！！！

**Comment by RQuispeC** [comment]
Hi, 
can you share the command you run and the error trace? this is a weird error. Also, are you using GPU? did you modify the code?

**Comment by syh-hue** [comment]
ye,I used GPU,I didn't modify the code.But I run it on pycharm and not linux.Follow my error:
Traceback (most recent call last):
  File "G:\syh\envs\pytorch\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "F:\workspace\top-dropblock-master\torchreid\engine\engine.py", line 260, in _evaluate
    dropmask = self._extract_drop_masks(imgs, visdrop, visdroptype)
  File "F:\workspace\top-dropblock-master\torchreid\engine\engine.py", line 636, in _extract_drop_masks
    outputs = self.model(input, drop_top=drop_top, visdrop=visdrop)
  File "G:\syh\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:\syh\envs\pytorch\lib\site-packages\torch\nn\parallel\data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "G:\syh\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'drop_top'
————————If I do some change such as     
——def _extract_drop_masks(self, input, visdrop, visdroptype):
        self.model.eval()
        drop_top = (visdroptype == 'top')
        outputs = self.model(input, drop_top=drop_top, visdrop=visdrop)
        outputs = outputs.mean(1)
        masks = []
——————
modify the **outputs = self.model(input, drop_top=drop_top, visdrop=visdrop)**into
                  **outputs = self.model(input, drop_top, visdrop)**
it errored TypeError: forward() takes 2 or 3 positional arguments but 4 were given.And I didn't modify torch's module.py.

**Comment by syh-hue** [comment]
> 嗨，
> 你能分享你运行的命令和错误跟踪吗？这是一个奇怪的错误。另外，你用的是GPU吗？你修改代码了吗？
when run main.py,and wo didn't understand Train and Test in README.md.Such as 
python main.py \
--config-file configs/im_top_bdnet_train_market1501.yaml \  ### I update it in main.py  **parser.add_argument('--config-file', type=str, default='', help='path to config file')**?
--root $PATH_TO_DATA————update**parser.add_argument('--root', type=str, default='', help='path to data root')**？
If I only test 
To test Top-DBnet, update configs/im_top_bdnet_test.yaml with the dataset name and path to saved model:
model:
    load_weights: $PATH_TO_MODEL
test:
    rerank: False # Update this if you want to use re-ranking
    visrank: False # Update this if you want to visualize activation maps
    targets: ['cuhk03'] # Dataset name, e.g. ('cuhk03', 'market1501', 'dukemtmcreid')
I updated it

**Comment by RQuispeC** [comment]
I think I understand the error now, `engine.py` calls the model (`self.model(input, drop_top, visdrop)`) assuming that in the forward function it supports the parameter `drop_top`. For instance, our network implementation is in [here](https://github.com/RQuispeC/top-dropblock/blob/master/torchreid/models/bdnet.py) and you can see that the forward function has a parameter `drop_top`. However, other models that are available in the repo (but we don't use) doesn't accept this parameter (e.g., [this](https://github.com/RQuispeC/top-dropblock/blob/master/torchreid/models/densenet.py)). 
I think you are changing the model.name parameter in the config file and that's triggering the error, please double check you are using a model that has the parameter `drop_top` on the forward implementation.

About train and test. what is not clear?
to train our original model for market1501 dataset you should do
```
python main.py \
--config-file configs/im_top_bdnet_train_market1501.yaml \
--root $PATH_TO_DATA
```
changing `$PATH_TO_DATA` to the path of your local version of market1501 dataset.

To test you need to run 
```
python main.py \
--config-file configs/m_top_bdnet_test.yaml \
--root $PATH_TO_DATA
```
but before you do so, specify the path of the trained model on the `config/m_top_bdnet_test.yaml` file and make use you are using the correct dataset, for instance

```
model:
    load_weights: $PATH_TO_PRETRAINED_MODEL

test:
    targets: ['market1501'] # Dataset name, e.g. ('cuhk03', 'market1501', 'dukemtmcreid')
```

if you are interested in visualizing activations/rank/re-rank you can specify that on the conf file too with

```
test:
    rerank: True
    visrank: True
```

**Comment by RQuispeC** [comment]
BTW, trained models are available [here](https://drive.google.com/drive/folders/1GJLUnYw-UUyM6kgJHCeFszxq3_3JTeTy?usp=sharing)

**Comment by syh-hue** [comment]
> I think I understand the error now, `engine.py` calls the model (`self.model(input, drop_top, visdrop)`) assuming that in the forward function it supports the parameter `drop_top`. For instance, our network implementation is in [here](https://github.com/RQuispeC/top-dropblock/blob/master/torchreid/models/bdnet.py) and you can see that the forward function has a parameter `drop_top`. However, other models that are available in the repo (but we don't use) doesn't accept this parameter (e.g., [this](https://github.com/RQuispeC/top-dropblock/blob/master/torchreid/models/densenet.py)).
> I think you are changing the model.name parameter in the config file and that's triggering the error, please double check you are using a model that has the parameter `drop_top` on the forward implementation.
> 
> About train and test. what is not clear?
> to train our original model for market1501 dataset you should do
> 
> ```
> python main.py \
> --config-file configs/im_top_bdnet_train_market1501.yaml \
> --root $PATH_TO_DATA
> ```
> 
> changing `$PATH_TO_DATA` to the path of your local version of market1501 dataset.
> 
> To test you need to run
> 
> ```
> python main.py \
> --config-file configs/m_top_bdnet_test.yaml \
> --root $PATH_TO_DATA
> ```
> 
> but before you do so, specify the path of the trained model on the `config/m_top_bdnet_test.yaml` file and make use you are using the correct dataset, for instance
> 
> ```
> model:
>     load_weights: $PATH_TO_PRETRAINED_MODEL
> 
> test:
>     targets: ['market1501'] # Dataset name, e.g. ('cuhk03', 'market1501', 'dukemtmcreid')
> ```
> 
> if you are interested in visualizing activations/rank/re-rank you can specify that on the conf file too with
> 
> ```
> test:
>     rerank: True
>     visrank: True
> ```

That's ok! I GOT it! THANKS!!
