### ISSUE TITLE
How to evaluate on my data

### ISSUE THREAD

**Issue by kazuki-can** [RQuispeC/top-dropblock#8]
Hello again.
Thank you for providing the pre-trained model before.
I have a question.
I want to use this model on my data and I want to get the distance of similarity of each images.
For instance, I would like to see 
`image1 = 'image1.png'
 image2 = 'image2.png'
 image3 = 'image3.png'
 dintance = top_dropblock(image1,image2,image3)
`
Like distance[0] has the distance between image1 and image2 and distance[1] has the distance between image1 and image3.

**Comment by RQuispeC** [comment]
This repo doesn't have an implementation for such a function, you will need to do it yourself. Feel free to create a PR when you are done with this.
Some pointers to steps to follow:
- Load the images and parse them to the expected network input format:
Take a look at [datamanager](https://github.com/RQuispeC/top-dropblock/blob/master/torchreid/data/datamanager.py)
- Get features from inputs on the previous step:
Take a look at [test](https://github.com/RQuispeC/top-dropblock/blob/master/torchreid/engine/engine.py)
- Calculate distance based on features:
Take a look at [`compute_distance_matrix`](https://github.com/RQuispeC/top-dropblock/blob/master/torchreid/metrics/distance.py)

**Comment by kazuki-can** [comment]
Thank you for your support.
I will make the function and I'll ask you when I have no idea for what I want.

**Comment by kazuki-can** [comment]
At first step above, do I have to change ImageDataManager in datamanager.py?
I want to try this model for my 3 images and see the distance matrix.
I wrote this
`datamanager = torchreid.data.ImageDataManager(
        root='eval_folders/images',
        height=256,
        width=128,
        batch_size_train=32,
        batch_size_test=32
    )`
But it didn't work.
Thank you.

**Comment by kazuki-can** [comment]
"root" folder should have both query images and gallery images?

**Comment by RQuispeC** [comment]
`root` is where all the predefined datasets (e.g. Market1501, CUHK03 ...) are, then the script will automatic load one of them based on parameters `--sources` and `--targets`.  Using torchreid.data.ImageDataManager should be fine but you need to define your dataset in the `datasets` [directory](https://github.com/RQuispeC/top-dropblock/tree/master/torchreid/data/datasets/image). Refer to #5 

Please check `main.py` to understand how the data and parameters flow in the repo.

**Comment by kazuki-can** [comment]
Thanks for your help.
I probably got the distance matrix.
My query has 11 images and my gallery has 104 images for 13 people.
When I show 'dismat' in 'engine.py', it says
`[[ 626.0591   827.6196   846.8381  ... 1131.6605   895.0611   896.70605]
 [ 647.6859   843.34717  864.7979  ... 1151.5863   925.90814  923.80066]
 [ 697.20215  875.4114   902.0261  ... 1205.2034   977.14856  958.08295]
 ...
 [ 844.1223  1003.6997  1030.9075  ... 1327.8502  1080.5339  1025.8748 ]
 [ 899.0913  1068.1633  1095.0132  ... 1371.1497  1134.3245  1066.7097 ]
 [ 943.7534  1094.2499  1105.1289  ... 1358.9064  1147.7786  1070.4844 ]]`
Does this mean I did it right?
And the first number '626.0591' means the distance between the first query image and the first gallery image?
Thank you.

**Comment by RQuispeC** [comment]
you can print the size of dismat and it should be of size 13x104 or 104x13. Either way, your assumptions is correct: each element in the dismat is the distance between query i and galley j.

**Comment by kazuki-can** [comment]
Its size is 13x104 so I think this is correct way.
Thanks to your advice, I could do it.
I appreciate it very much.
Thank you.
